// Auto-generated by scripts/build-gallery-data.mjs — do not edit by hand.
// Re-run `npm run gallery:build` after adding images to public/gallery/.

export type GalleryItem = {
  src: string;
  title: string;
  category: string;
  categorySlug: string;
  w: number;
  h: number;
};

export const galleryCategories: { slug: string; label: string }[] = [
  { slug: "featured", label: "Featured" },
  { slug: "event", label: "Event & Competition" },
  { slug: "logo", label: "Logo Design" },
  { slug: "print", label: "Print & Collateral" },
  { slug: "social", label: "Social Media" },
  { slug: "shirts", label: "T-Shirt & Apparel" },
];

export const galleryItems: GalleryItem[] = [
  {
    "src": "/gallery/featured/certificate.png",
    "title": "Certificate",
    "category": "Featured",
    "categorySlug": "featured",
    "w": 3508,
    "h": 2480
  },
  {
    "src": "/gallery/featured/cmo-banner.png",
    "title": "Cmo Banner",
    "category": "Featured",
    "categorySlug": "featured",
    "w": 2460,
    "h": 936
  },
  {
    "src": "/gallery/featured/cmo-logo.png",
    "title": "Cmo Logo",
    "category": "Featured",
    "categorySlug": "featured",
    "w": 6783,
    "h": 2036
  },
  {
    "src": "/gallery/featured/cmo-profile.png",
    "title": "Cmo Profile",
    "category": "Featured",
    "categorySlug": "featured",
    "w": 1000,
    "h": 1000
  },
  {
    "src": "/gallery/featured/display.png",
    "title": "Display",
    "category": "Featured",
    "categorySlug": "featured",
    "w": 1920,
    "h": 1080
  },
  {
    "src": "/gallery/featured/start.png",
    "title": "Start",
    "category": "Featured",
    "categorySlug": "featured",
    "w": 1920,
    "h": 1080
  },
  {
    "src": "/gallery/event/battle-results-prev.png",
    "title": "Battle Results",
    "category": "Event & Competition",
    "categorySlug": "event",
    "w": 1920,
    "h": 1080
  },
  {
    "src": "/gallery/event/bracket.png",
    "title": "Bracket",
    "category": "Event & Competition",
    "categorySlug": "event",
    "w": 1920,
    "h": 1080
  },
  {
    "src": "/gallery/event/display.png",
    "title": "Display",
    "category": "Event & Competition",
    "categorySlug": "event",
    "w": 1920,
    "h": 1080
  },
  {
    "src": "/gallery/event/instant-replay-test.png",
    "title": "Instant Replay",
    "category": "Event & Competition",
    "categorySlug": "event",
    "w": 1920,
    "h": 1080
  },
  {
    "src": "/gallery/event/loading-screen-prev.png",
    "title": "Loading Screen",
    "category": "Event & Competition",
    "categorySlug": "event",
    "w": 1920,
    "h": 1080
  },
  {
    "src": "/gallery/event/loading-screen-test.png",
    "title": "Loading Screen",
    "category": "Event & Competition",
    "categorySlug": "event",
    "w": 1920,
    "h": 1080
  },
  {
    "src": "/gallery/event/match-overlay-prev.png",
    "title": "Match Overlay",
    "category": "Event & Competition",
    "categorySlug": "event",
    "w": 1920,
    "h": 1080
  },
  {
    "src": "/gallery/event/match-overlay.png",
    "title": "Match Overlay",
    "category": "Event & Competition",
    "categorySlug": "event",
    "w": 1920,
    "h": 1080
  },
  {
    "src": "/gallery/event/match-sched.png",
    "title": "Match Sched",
    "category": "Event & Competition",
    "categorySlug": "event",
    "w": 1920,
    "h": 1080
  },
  {
    "src": "/gallery/event/roster-prev.png",
    "title": "Roster",
    "category": "Event & Competition",
    "categorySlug": "event",
    "w": 1920,
    "h": 1080
  },
  {
    "src": "/gallery/logo/dce-logo.png",
    "title": "Dce Logo",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/logo/emerald-hamony-text.png",
    "title": "Emerald Hamony Text",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 1679,
    "h": 432
  },
  {
    "src": "/gallery/logo/emerald-harmony-logo.png",
    "title": "Emerald Harmony Logo",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 493,
    "h": 628
  },
  {
    "src": "/gallery/logo/jeizi-production.png",
    "title": "Jeizi Production",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 536,
    "h": 510
  },
  {
    "src": "/gallery/logo/linguists-society-1.png",
    "title": "Linguists Society 1",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 3103,
    "h": 926
  },
  {
    "src": "/gallery/logo/lnk-kalap-cup-logo-textured.png",
    "title": "Lnk Kalap Cup Logo Textured",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 2163,
    "h": 1966
  },
  {
    "src": "/gallery/logo/lnk-naujan.png",
    "title": "Lnk Naujan",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 9883,
    "h": 3863
  },
  {
    "src": "/gallery/logo/mibt-logo-1.png",
    "title": "Mibt Logo 1",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 9508,
    "h": 4317
  },
  {
    "src": "/gallery/logo/mlbb-balite-tournament-2025.png",
    "title": "Mlbb Balite Tournament 2025",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/logo/myfi-converge-invitational-logo-v2.png",
    "title": "Myfi Converge Invitational Logo",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 1657,
    "h": 974
  },
  {
    "src": "/gallery/logo/palhi-tournament-logo.png",
    "title": "Palhi Tournament Logo",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 4252,
    "h": 2405
  },
  {
    "src": "/gallery/logo/sali-talon.png",
    "title": "Sali Talon",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 5674,
    "h": 5665
  },
  {
    "src": "/gallery/logo/ultra-esports-text-1.png",
    "title": "Ultra Esports Text 1",
    "category": "Logo Design",
    "categorySlug": "logo",
    "w": 3407,
    "h": 3361
  },
  {
    "src": "/gallery/print/board-champion.png",
    "title": "Board Champion",
    "category": "Print & Collateral",
    "categorySlug": "print",
    "w": 6600,
    "h": 2400
  },
  {
    "src": "/gallery/print/certificate-jeizi.png",
    "title": "Certificate Jeizi",
    "category": "Print & Collateral",
    "categorySlug": "print",
    "w": 3508,
    "h": 2480
  },
  {
    "src": "/gallery/print/certificate-lnk.png",
    "title": "Certificate Lnk",
    "category": "Print & Collateral",
    "categorySlug": "print",
    "w": 2480,
    "h": 3508
  },
  {
    "src": "/gallery/print/certificate-template.png",
    "title": "Certificate Template",
    "category": "Print & Collateral",
    "categorySlug": "print",
    "w": 3508,
    "h": 2480
  },
  {
    "src": "/gallery/print/i-book-cover.png",
    "title": "I Book Cover",
    "category": "Print & Collateral",
    "categorySlug": "print",
    "w": 5100,
    "h": 3300
  },
  {
    "src": "/gallery/print/iii-iv-about-ver-4.png",
    "title": "Iii Iv About Ver 4",
    "category": "Print & Collateral",
    "categorySlug": "print",
    "w": 5100,
    "h": 3300
  },
  {
    "src": "/gallery/print/lpt-na-babbyy-kooo.png",
    "title": "Lpt Na Babbyy Kooo",
    "category": "Print & Collateral",
    "categorySlug": "print",
    "w": 1920,
    "h": 1440
  },
  {
    "src": "/gallery/print/plake.png",
    "title": "Plake",
    "category": "Print & Collateral",
    "categorySlug": "print",
    "w": 4075,
    "h": 6086
  },
  {
    "src": "/gallery/print/tarp-design-v2.png",
    "title": "Tarp Design",
    "category": "Print & Collateral",
    "categorySlug": "print",
    "w": 1920,
    "h": 1152
  },
  {
    "src": "/gallery/social/1-day.png",
    "title": "1 Day",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1000,
    "h": 1000
  },
  {
    "src": "/gallery/social/5.png",
    "title": "5",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1080,
    "h": 1080
  },
  {
    "src": "/gallery/social/6.png",
    "title": "6",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1080,
    "h": 1080
  },
  {
    "src": "/gallery/social/7.png",
    "title": "7",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1080,
    "h": 1080
  },
  {
    "src": "/gallery/social/11.png",
    "title": "11",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1080,
    "h": 1080
  },
  {
    "src": "/gallery/social/12.png",
    "title": "12",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1080,
    "h": 1080
  },
  {
    "src": "/gallery/social/15.png",
    "title": "15",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1080,
    "h": 1080
  },
  {
    "src": "/gallery/social/16.png",
    "title": "16",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1080,
    "h": 1080
  },
  {
    "src": "/gallery/social/17.png",
    "title": "17",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1080,
    "h": 1080
  },
  {
    "src": "/gallery/social/18.png",
    "title": "18",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1080,
    "h": 1080
  },
  {
    "src": "/gallery/social/cover-photo.png",
    "title": "Cover Photo",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1702,
    "h": 630
  },
  {
    "src": "/gallery/social/profile-pic-2.png",
    "title": "Profile Pic 2",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 2048,
    "h": 2048
  },
  {
    "src": "/gallery/social/pubmat.png",
    "title": "Pubmat",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 2000,
    "h": 2000
  },
  {
    "src": "/gallery/social/pubmatlnk.png",
    "title": "Pubmatlnk",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 2000,
    "h": 2000
  },
  {
    "src": "/gallery/social/sk-interbarangay-mlb.png",
    "title": "Sk Interbarangay Mlb",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1000,
    "h": 1000
  },
  {
    "src": "/gallery/social/standings.png",
    "title": "Standings",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 2000,
    "h": 2400
  },
  {
    "src": "/gallery/social/story-1.png",
    "title": "Story 1",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 720,
    "h": 1280
  },
  {
    "src": "/gallery/social/story-2.png",
    "title": "Story 2",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 720,
    "h": 1280
  },
  {
    "src": "/gallery/social/teams.png",
    "title": "Teams",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 2000,
    "h": 2400
  },
  {
    "src": "/gallery/social/tournament-champ-copy.png",
    "title": "Tournament Champ",
    "category": "Social Media",
    "categorySlug": "social",
    "w": 1000,
    "h": 1000
  },
  {
    "src": "/gallery/shirts/1.png",
    "title": "1",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/shirts/2.png",
    "title": "2",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/shirts/3.png",
    "title": "3",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/shirts/4.png",
    "title": "4",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/shirts/5-1.png",
    "title": "5 1",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/shirts/5-2.png",
    "title": "5 2",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/shirts/6.png",
    "title": "6",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/shirts/6d-away.png",
    "title": "6d Away",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 3600,
    "h": 2389
  },
  {
    "src": "/gallery/shirts/6d-home.png",
    "title": "6d Home",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 3600,
    "h": 2389
  },
  {
    "src": "/gallery/shirts/7.png",
    "title": "7",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/shirts/8.png",
    "title": "8",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/shirts/9.png",
    "title": "9",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/shirts/10.png",
    "title": "10",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 4000,
    "h": 4000
  },
  {
    "src": "/gallery/shirts/apex-landscaping.png",
    "title": "Apex Landscaping",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 3600,
    "h": 2389
  },
  {
    "src": "/gallery/shirts/black-legits.png",
    "title": "Black Legits",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 3600,
    "h": 2389
  },
  {
    "src": "/gallery/shirts/legits-club-shirt.png",
    "title": "Legits Club Shirt",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 3600,
    "h": 2389
  },
  {
    "src": "/gallery/shirts/lnk-mockup.png",
    "title": "Lnk Mockup",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 3600,
    "h": 2389
  },
  {
    "src": "/gallery/shirts/sample.png",
    "title": "Sample",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 3600,
    "h": 2389
  },
  {
    "src": "/gallery/shirts/sk-fed-mockup.png",
    "title": "Sk Fed Mockup",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 3600,
    "h": 2389
  },
  {
    "src": "/gallery/shirts/usg-mcc.png",
    "title": "Usg Mcc",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 3600,
    "h": 2389
  },
  {
    "src": "/gallery/shirts/whitelegits.png",
    "title": "Whitelegits",
    "category": "T-Shirt & Apparel",
    "categorySlug": "shirts",
    "w": 3600,
    "h": 2389
  },
];
